default["getmail"]["retrvr_type"] = "SimplePOP3Retriever"
default["getmail"]["verbose_level"] = "2"
default["getmail"]["read_all"] = "false"
default["getmail"]["delete_after"] = "3"
default["getmail"]["message_log "] = "/var/log/getmail/gm.log"
